### PR TITLE
Make vat ID detector return an empty data set if there are no words

### LINKED ISSUE #75: NoMethodError in VatNumberDetector
When there are no words found at all, the VatNumberDetector crashes:

```
NoMethodError: undefined method `*' for nil:NilClass
/myapp/lib/detectors/vat_number_detector.rb:27:in `find_vat_numbers'
```

Bill: PYdefyzCHkSp9atMY.jpg (empty Image)

### PR DESCRIPTION
**Pull request by tamacodechi**
closes #75

### CODE REVIEW

File: lib/bill_recognizer.rb [hunk 1]
```diff
@@ -104,7 +104,7 @@ def recognize
     #        bottom: #{word.bottom}
     #        "
     #      }
-
+
```
Comment (clemenshelm) [inline lib/bill_recognizer.rb]: No whitespace, please 😄

Comment (clemenshelm) [reply lib/bill_recognizer.rb]: Doesn't Rubocop lint this?

**Review by clemenshelm — CHANGES_REQUESTED** [review]

File: lib/bill_recognizer.rb (hunk 1 above)
Comment (tamacodechi) [reply lib/bill_recognizer.rb]: Strange thing is that it allowed it and it wouldn't pass the CI tests if it didn't. I also spotted this when I was creating the PR but I thought it was harmless since Rubocop didn't mind. I can remove it 😉

**Review by clemenshelm — APPROVED** [review]
