### PR TITLE
Report error when PDF cannot be read.

### LINKED ISSUE #137: Handle invalid pdfs gracefully
At the moment, PDFs which cannot be read lead to an exception like

```
NoMethodError: undefined method `page' for nil:NilClass
/myapp/lib/image_processor.rb:12:in `initialize'
```

Instead of failing with an exception, the recognizer should write an error back to the web app informing it about the problem.

Bills with invalid PDFs:
- [x] 5CCkGCCprokPBy2o6.pdf
- [x] CHhrbRhWvLofrWMDQ.pdf
- [x] 7vEgEHxN5cWQP8Tq7.pdf

### PR DESCRIPTION
**Pull request by clemenshelm**
Closes #137

### CODE REVIEW

File: spec/bill_recognizer_spec.rb [hunk 1]
```diff
@@ -11,4 +11,12 @@
 
     expect(recognizer.recognize[:error]).to eq 'Unprocessable file type: .p7s'
   end
+
+  it 'reports when a bill cannot be read' do
+    # This spec will fail once Ghostscript supports this crappy PDF. Awesome!
```
Comment (tamacodechi) [inline spec/bill_recognizer_spec.rb:16]: Great comment, because now when it does fail we will know why without having to dig around 👍

File: lib/image_processor.rb [hunk 2]
```diff
@@ -2,13 +2,15 @@
...
 class ImageProcessor
+  class InvalidImage < StandardError; end
   include Magick
 
   def initialize(image_path)
     # Only read first page of bill
     image_path = "#{image_path}[0]"
     begin
       original_image = Image.read(image_path)[0]
+      raise InvalidImage, 'Cannot read image.' unless original_image
```
Comment (tamacodechi) [inline lib/image_processor.rb]: Should the error be more descriptive? If this is in the case of PDF only then maybe something like "Cannot read image. Unsupported PDF." might be a little more descriptive 😀

**Review by tamacodechi — COMMENTED** [review]
Awesome 😉  This isn't the case when the recognizer gives out that big block of text when leading a PDF, is it? (I ask because those still spit out recognized words, so I'm wondering if I've ever encountered an unsupported PDF)

**Review by tamacodechi — CHANGES_REQUESTED** [review]
The new test in ```spec/bill_recognizer_spec.rb``` doesn't pass 🙈

File: lib/image_processor.rb (hunk 2 above)
Comment (clemenshelm) [reply lib/image_processor.rb]: It might be more descriptive, but it also might be wrong. If there is no image, it doesn't necessarily mean there's an error with the PDF. It could also be a JPG or a PNG in an invalid format. So I'd rather go with being more generic than with being more specific, but wrong 😉

**Comment by clemenshelm** [comment]
No, the big block of text are probably just warnings. If the PDF is invalid, it won't be able to recognize anything because there won't be an image.

File: lib/image_processor.rb (hunk 2 above)
Comment (tamacodechi) [reply lib/image_processor.rb]: Ahh makes sense, I meant it more as an example where we extract the extension. So we can't really pass the file extension because it might simply be in the incorrect format? Then again the words "unsupported" kind of indicate that it is an unsupported file of that extension, and in the case of pngs and jpgs we know that it is that they're in an invalid format?

**Comment by tamacodechi** [comment]
Yeah that I got I meant more that the spec isn't getting what it expected on Codeship. Odd, I fetched your branch and it all passed on my machine, so I would chalk it up to the environment on Codeship, right?

**Comment by clemenshelm** [comment]
Just to clarify why there are so many commits and strange new files: I changed Codeship to use Docker to give us full control over the library versions we use (because there was a different version of Ghostscript used which made the test fail).

**Review by tamacodechi — APPROVED** [review]
I'd love to pick your brain on some of the changes but seeing as merging this is kinda urgent I'll approve first and ask questions later, because I don't see any changes that need to be made 👍

**Comment by clemenshelm** [comment]
Ok, I merged it 😄 

Feel free to comment and I'll answer! 😉
