### PR TITLE
333 missing prices

### LINKED ISSUE #333: missing prices
- In the bill 2BWLcAHqKAJTzwSDC.jpg a lot of prices are not in detected and therefore are missing in the yml file.

Prices that are detected: 5.34;  0.49;   4.85;  300

bildschirmfoto vom 2017-08-08 16-22-26

- In fRN7LRFs8ZRyyeFdE.pdf the MwSt value was not detected, but it should be.

- In FvK6uW7F9A62f4YGZ.pdf the value "41.02" should be detected 4 times, but was only detected twice.

- In C5sri9hxpbDhha68D.png the value "23,55" should be detected 2 times, but was not detected

- In rDxLnivxoXQw9nWa7.pdf the values "431.25" and "86.25" are not detecetd

- In LcW5EsYpEX7FTsUF3.jpg the value "8.29" is missing

### LINKED ISSUE #361: wrong text-box dimensions
We still have some "artifacts" recognized as text. To get the best possible results, we need to filter them out.

Examples:
- cN6h5XBq6howTHQwa.pdf (text_box_top = 0, text_box_left = 0,text_box_right and text_box_bottom are to big)

### PR DESCRIPTION
**Pull request by Tr4in**
Closes #333 
Closes #361 

I think that the syntax has to be corrected!

### CODE REVIEW

File: lib/detectors/date_detector.rb [hunk 1]
```diff
@@ -37,7 +37,7 @@ def self.filter
 
   def self.filter_out_interefering_date_terms
     words = find_dates(Word.all, LONG_SLASH_DATE_REGEX, max_words: 1)
-    words += find_dates(Word.all, SHORT_PERIOD_DATE_REGEX, max_words: 2)
+    words += find_dates(Word.all, SHORT_PERIOD_DATE_REGEX, max_words: 6)
```
Comment (tamacodechi) [inline lib/detectors/date_detector.rb:40]: 👍

File: lib/detectors/price_detector.rb [hunk 2]
```diff
@@ -17,13 +19,28 @@ class PriceDetector
   def self.filter_out_quantity_column
     %w(Menge Anz.).each do |quantity_text|
       quantity = Word.first(text: quantity_text)
-      PriceTerm.where { right <= quantity.right }.destroy if quantity
+      next unless quantity
+      PriceTerm.map do |term|
```
Comment (tamacodechi) [inline lib/detectors/price_detector.rb]: Is `.map` necessary? I think `.each` should be enough, or?

File: spec/detectors/date_detector_spec.rb [hunk 3]
```diff
@@ -775,8 +775,60 @@
     expect(date_strings(dates)).to be_empty
   end
 
+  it 'detects dates with max_words 6' do
```
Comment (tamacodechi) [inline spec/detectors/date_detector_spec.rb]: "consisting of 6 words"

It's a little odd to have the attribute name there 😅

File: lib/models/word.rb [hunk 4]
```diff
@@ -8,14 +8,14 @@ class Word < Sequel::Model
...
-  UNITS = %w(kg % Stunden SK PA SG ST TO KG M3).freeze
+  UNITS = %w(kg % Stunden SK PA SG ST TO KG M3 MWST).freeze
 
   def next
     Word[id + 1]
   end
 
   def follows(previous_word)
-    max_space_width = previous_word.height * 1.80
+    max_space_width = previous_word.height * 10.0
```
Comment (tamacodechi) [inline lib/models/word.rb:18]: Can't wait 'til we stop using `.follows` 😅 This fixes the current problem though. Have you noticed any change in acceptance test results? Like the terms that get picked up and so on

File: lib/detectors/price_detector.rb [hunk 5]
```diff
@@ -17,13 +19,28 @@ class PriceDetector
...
+        term.destroy if in_same_column(quantity, term)
```
Comment (tamacodechi) [inline lib/detectors/price_detector.rb]: 👏 👏 👏

File: lib/detectors/price_detector.rb [hunk 6]
```diff
@@ -17,13 +19,28 @@ class PriceDetector
...
+  end
+
+  def self.filter_out_dates
+    PriceTerm.map do |term|
+      first_word = Word.right_after(term)
+
+      next unless first_word && first_word.text.match(/\./)
+      second_word = Word.right_after(first_word)
+      term.destroy if second_word &&
+                      second_word.text.match(/^(\d{2})$/)
```
Comment (tamacodechi) [inline lib/detectors/price_detector.rb]: It might be nice to extend dimensionable with a method with this behaviour 😊 I can see many cases where we could use this 😋 It's also loosely defined here and it feels like it's not really behaviour that a detector should define, right?

File: spec/detectors/price_detector_spec.rb [hunk 7]
```diff
@@ -1018,6 +1018,159 @@
     expect(prices.map(&:text)).to eq ['2,17€']
   end
 
+  it 'detects prices which are not in between of quantity' do
```
Comment (tamacodechi) [inline spec/detectors/price_detector_spec.rb]: "which are not in part of a quantity"

**Review by tamacodechi — CHANGES_REQUESTED** [review]
Very nice 😉

File: lib/models/dimensionable.rb [hunk 8]
```diff
@@ -48,6 +48,17 @@ def right_above(current)
       everything_above.last
     end
 
+    def match_two_words_after(current, regex1, regex2)
```
Comment (tamacodechi) [inline lib/models/dimensionable.rb]: `.two_word_after_matches?`

Comment (tamacodechi) [reply lib/models/dimensionable.rb]: This returns true or false 🎉

File: lib/bill_recognizer.rb [hunk 9]
```diff
@@ -139,6 +138,7 @@ def recognize_words(png_file)
 
     hocr_doc = Nokogiri::HTML(hocr)
     create_words_from_hocr(hocr_doc)
+    Word.filter_out_artifacts
   end
```
Comment (tamacodechi) [inline lib/bill_recognizer.rb:142]: "Closes #361 " 🥇

File: spec/detectors/date_detector_spec.rb [hunk 10]
```diff
@@ -775,8 +775,60 @@
     expect(date_strings(dates)).to be_empty
   end
 
+  it 'detects dates which consists of 6 words' do
+    # From C5sri9hxpbDhha68D.png
+
```
Comment (tamacodechi) [inline spec/detectors/date_detector_spec.rb]: 👀

**Review by tamacodechi — CHANGES_REQUESTED** [review]
🌮

**Review by tamacodechi — APPROVED** [review]
👏 👏 👏 👏 👏 👏 👏 👏 👏 👏
