### PR TITLE
fixed future dates

### LINKED ISSUE #206: Fix future dates
The bills `vGmK76dSSMrLQ8axN.pdf` and `rokPNRvjveNpX62jB.pdf` both have excellent recognition results however they both have an incorrect invoice date set in the future.

### PR DESCRIPTION
**Pull request by Tr4in**
Closes #206

### CODE REVIEW

File: lib/detectors/date_detector.rb [hunk 1]
```diff
@@ -25,12 +25,12 @@ def self.filter
     reduced_words = filter_out_interefering_date_terms
     find_long_dates_with_periods(reduced_words)
 
+    find_multi_word_dates(reduced_words)
```
Comment (tamacodechi) [inline lib/detectors/date_detector.rb:28]: Does the test you added need this change to pass? 😅 
If so, please change the name to reflect that. Thanks 👍

**Review by tamacodechi — CHANGES_REQUESTED** [review]
Please autogenerate the rubocop todo :) `to_datetime` being one line longer is making rubocop angry 😉

File: spec/detectors/date_detector_spec.rb [hunk 2]
```diff
@@ -324,6 +324,38 @@
...
+    )
+
+    create(
+      :word,
+      text: '2017',
+      left: 0.06833333333333333,
+      right: 0.09666666666666666,
+      top: 0.5585394581861013,
+      bottom: 0.5656065959952886
+    )
```
Comment (tamacodechi) [inline spec/detectors/date_detector_spec.rb:354]: Can you add a blank line after this parethesis? That way it looks just as nice as all our other tests 😂

File: spec/detectors/date_detector_spec.rb [hunk 3]
```diff
@@ -712,6 +746,48 @@
...
+
+    create(
+      :word,
+      text: '51/5/38',
+      left: 0.5363219895287958,
+      right: 0.5765706806282722,
+      top: 0.005319148936170213,
+      bottom: 0.01156336725254394
+    )
```
Comment (tamacodechi) [inline spec/detectors/date_detector_spec.rb:785]: I don't think this should get detected at all 🤔
It's not a date.

**Review by tamacodechi — CHANGES_REQUESTED** [review]

File: spec/detectors/date_detector_spec.rb (hunk 3 above)
Comment (Tr4in) [reply spec/detectors/date_detector_spec.rb:785]: Although it is not a valid date it matches short slash regex

Comment (tamacodechi) [reply spec/detectors/date_detector_spec.rb:785]: You could limit the regex to accept dates from this decade for now :) I guess this solution won't work for all cases but it'll work for now

**Review by tamacodechi — CHANGES_REQUESTED** [review]
Please update the rubocop todo ;)

File: spec/detectors/date_detector_spec.rb (hunk 3 above)
Comment (clemenshelm) [reply spec/detectors/date_detector_spec.rb:785]: I'd prefer not to, the decade isn't that long anymore and I'd like to avoid that things stop all of a sudden on Jan 1, 2020 😉

Comment (clemenshelm) [reply spec/detectors/date_detector_spec.rb:785]: The fact that there's `51` and `38` disqualifies it as a date as only one of them can be a year. Please update the regex appropriately.

Comment (tamacodechi) [reply spec/detectors/date_detector_spec.rb:785]: I was thinking that too, and also there might be non dates that fall into this decade, so it's not a very healthy solution 😔

**Review by tamacodechi — APPROVED** [review]
