### PR TITLE
332 wrong text box dimensions

### LINKED ISSUE #332: Wrong text-box dimensions
The dimensions of the text-box are sometimes wrong. Maybe there are some "artifacts" recognized as text. 

Example bill: 
- 4gf87ndsAgDhTjZmg.pdf  (text_box_top = 0, which is incorrect)
- QcgqQs8d5bkLqs65q.pdf (text_box_bottom > 1!!)
- iLWtAEvMEtQw2bauv.pdf (text_box_left = 0!, should be around 0.05)
- T62xs4gCJ4WtCZrbh.pdf (text_box_right > 1!)
- bRrcBNr9ma9RnXoFT.pdf (text_box_bottom >1, text_box_right >1)

### PR DESCRIPTION
**Pull request by Tr4in**
Closes #332

### CODE REVIEW

File: lib/image_processor.rb [hunk 1]
```diff
@@ -61,13 +60,22 @@ def apply_background(color)
...
   end
 
   def normalize
     process_image(&:normalize)
   end
 
+  def update_width_and_height
+    @image_width = @image.columns
+    @image_height = @image.rows
+  end
```
Comment (tamacodechi) [inline lib/image_processor.rb:77]: 💖

File: lib/models/word.rb [hunk 2]
```diff
@@ -18,4 +18,9 @@ def follows(previous_word)
     # space: #{max_space_width} => last: #{previous_word.left}"
     previous_word.right + max_space_width >= left
   end
+
+  def self.filter_out_artifacts
+    # Filter Conditions
```
Comment (tamacodechi) [inline lib/models/word.rb]: I don't think this comment is necessary, if the code is good, it explains itself :)

File: lib/models/word.rb [hunk 3]
```diff
@@ -18,4 +18,9 @@ def follows(previous_word)
...
+    where(text: [' ', '*'])&.destroy
```
Comment (tamacodechi) [inline lib/models/word.rb]: Here you're removing the artefact words completely from our saved words?
🤔  @clemenshelm  do you think it's okay like this or should we be creating a subset of "desired" words instead?

File: lib/detectors/vat_number_detector.rb [hunk 4]
```diff
@@ -33,7 +33,7 @@ def find_vat_numbers(regex, after_each_word: nil)
         terms = Word.where(
           'bottom - top <= ?', median_height * scale_factor
         ).map do |word|
-          if term_stale || (last_word && !word.follows(last_word))
+          if term_stale
```
Comment (tamacodechi) [inline lib/detectors/vat_number_detector.rb]: Have you tried playing around with the `.follows` method instead of completely removing this here? I'm sure that condition was implemented for a reason 😉

File: lib/bill_recognizer.rb [hunk 5]
```diff
@@ -98,8 +98,12 @@ def recognize
     end
 
     recognize_words(png_file)
-    filter_words
+    Word.filter_out_artifacts
+
+    # ****** PRINT ALL WORDS ******
+    # print_words
```
Comment (tamacodechi) [inline lib/bill_recognizer.rb]: I think the method name "print_words" or `print_all words` or `print_all_detected words` is clear enough, the comment above is not necessary 😊

File: lib/bill_recognizer.rb [hunk 6]
```diff
@@ -136,16 +140,18 @@ def recognize_words(png_file)
...
+  def print_words
+    puts Word.map { |word|
+      "
+      text: \'#{word.text}\',
+      left: #{word.left},
+      right: #{word.right},
+      top: #{word.top},
+      bottom: #{word.bottom}
+      "
+    }
```
Comment (tamacodechi) [inline lib/bill_recognizer.rb:153]: 👍

File: spec/models/word_spec.rb [hunk 7]
```diff
@@ -87,4 +87,34 @@
 
     expect(word2.follows(word1)).to eq true
   end
+
+  it 'filters out words with blank space' do
```
Comment (tamacodechi) [inline spec/models/word_spec.rb]: You also filtered out an asterisk here, you should probably rename this to also describe that.

**Review by tamacodechi — CHANGES_REQUESTED** [review]
Awesome work 🌟 I think a review from @Thomas1e would be very useful here! Have you considered adding a spec that shows why the deskew cropping and updating of the dimensions is necessary? When we backtrack and look at the code it might not be so clear why we do that 🤔 A spec would be awesome 😋

File: lib/models/word.rb (hunk 3 above)
Comment (clemenshelm) [reply lib/models/word.rb]: It's ok. If we need these words at a later point, we can still save them. Personally I'd have filtered them out even before inserting them into the database, but I think it doesn't make much of a difference.

File: lib/models/word.rb [hunk 8]
```diff
@@ -13,14 +13,13 @@ def next
   end
 
   def follows(previous_word)
-    max_space_width = previous_word.height * 1.79
+    max_space_width = previous_word.height * 1.80
```
Comment (tamacodechi) [inline lib/models/word.rb:16]: 0.01 😂

File: lib/bill_recognizer.rb [hunk 9]
```diff
@@ -142,7 +141,7 @@ def recognize_words(png_file)
     create_words_from_hocr(hocr_doc)
   end
 
-  def print_words
+  def print_all_detected_words
```
Comment (tamacodechi) [inline lib/bill_recognizer.rb]: Just saw that it's after the words are filtered out, maybe just `print_all_words` since detected words includes the artefacts

File: spec/detectors/vat_number_detector_spec.rb [hunk 10]
```diff
@@ -828,7 +828,7 @@
     expect(vat_numbers.map(&:to_s)).to eq ['ATU65315367']
   end
 
-  it 'detects vats' do
+  it 'detects vats with high space width' do
```
Comment (tamacodechi) [inline spec/detectors/vat_number_detector_spec.rb]: Can you label this spec please? 😊

**Review by tamacodechi — CHANGES_REQUESTED** [review]

**Review by tamacodechi — APPROVED** [review]
